Show skills and domains example
hacking-thursday/yuan pull request #1
Opened 2018-01-22 05:37 UTC by a0726h77

2018-01-22 07:02 UTC, kjelly reviewed
Please update your code

2018-01-22 07:02 UTC, kjelly commented on src/App.js
> +    var projects = this.state.data.projects
Please indent

2018-01-22 07:02 UTC, kjelly commented on src/App.js
> +    if( this.state.data.projects != undefined) {
用這樣比較好

```
if( this.state.data.projects === undefined) {
  return empty
}
```

2018-01-24 13:49 UTC, a0726h77 commented
fixed

2018-01-24 13:59 UTC, kjelly requested changes
程式改完後，記得跑
node_modules/esformatter/bin/esformatter src/App.js -i
格式化程式碼。
那隻程式可用 npm install 安裝

2018-01-24 13:59 UTC, kjelly commented on src/App.js
> +          //skills_checkbox.push(<input type="checkbox" value={skills[i]} /> {skills[i]})
移除無用的註解吧

2018-01-24 13:59 UTC, kjelly commented on src/App.js
> +          //domains_checkbox.push(<input type="checkbox" value={domains[i]} /> {domains[i]})
移除無用的註解吧

2018-01-24 14:56 UTC, merged